<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('plants')->insert([
            [
                'name' => 'Aloe Vera',
                'scientific_name' => 'Aloe barbadensis miller',
                'image' => 'aloe_vera.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Great for skincare and medicinal uses.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Snake Plant',
                'scientific_name' => 'Sansevieria trifasciata',
                'image' => 'sansevieria_trifasciata.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Excellent air purifier.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spider Plant',
                'scientific_name' => 'Chlorophytum comosum',
                'image' => 'chlorophytum_comosum.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Loamy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Produces small white flowers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peace Lily',
                'scientific_name' => 'Spathiphyllum',
                'image' => 'spathiphyllum.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Shade',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Helps purify indoor air.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ZZ Plant',
                'scientific_name' => 'Zamioculcas zamiifolia',
                'image' => 'zamioculcas_zamiifolia.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Drought-tolerant and low maintenance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pothos',
                'scientific_name' => 'Epipremnum aureum',
                'image' => 'epipremnum_aureum.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Great for hanging baskets.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rubber Plant',
                'scientific_name' => 'Ficus elastica',
                'image' => 'ficus_elastica.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Can grow quite large indoors.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boston Fern',
                'scientific_name' => 'Nephrolepis exaltata',
                'image' => 'nephrolepis_exaltata.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Loamy',
                'fertilizing' => 'Bi-Weekly',
                'additional_info' => 'Prefers high humidity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fiddle-Leaf Fig',
                'scientific_name' => 'Ficus lyrata',
                'image' => 'ficus_lyrata.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Needs consistent conditions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monstera',
                'scientific_name' => 'Monstera deliciosa',
                'image' => 'monstera_deliciosa.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Known for its split leaves.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dracaena',
                'scientific_name' => 'Dracaena marginata',
                'image' => 'dracaena_marginata.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Tolerates low light.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Philodendron',
                'scientific_name' => 'Philodendron hederaceum',
                'image' => 'philodendron_hederaceum.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Easy to propagate.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peperomia',
                'scientific_name' => 'Peperomia obtusifolia',
                'image' => 'peperomia_obtusifolia.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Compact and bushy.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Calathea',
                'scientific_name' => 'Calathea lancifolia',
                'image' => 'calathea_lancifolia.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Shade',
                'soil_type' => 'Loamy',
                'fertilizing' => 'Bi-Weekly',
                'additional_info' => 'Loves humidity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dieffenbachia',
                'scientific_name' => 'Dieffenbachia seguine',
                'image' => 'dieffenbachia_seguine.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Also known as Dumb Cane.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aglaonema',
                'scientific_name' => 'Aglaonema commutatum',
                'image' => 'aglaonema_commutatum.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Also known as Chinese Evergreen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Syngonium',
                'scientific_name' => 'Syngonium podophyllum',
                'image' => 'syngonium_podophyllum.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Arrow-shaped leaves.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoya',
                'scientific_name' => 'Hoya carnosa',
                'image' => 'hoya_carnosa.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Produces fragrant flowers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oxalis',
                'scientific_name' => 'Oxalis triangularis',
                'image' => 'oxalis_triangularis.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Purple leaves and small white flowers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Begonia',
                'scientific_name' => 'Begonia rex',
                'image' => 'begonia_rex.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Known for colorful leaves.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fern',
                'scientific_name' => 'Polypodium vulgare',
                'image' => 'polypodium_vulgare.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Loamy',
                'fertilizing' => 'Bi-Weekly',
                'additional_info' => 'Prefers high humidity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cactus',
                'scientific_name' => 'Cactaceae',
                'image' => 'cactaceae.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Full Sun',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Drought-tolerant and low maintenance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Succulent',
                'scientific_name' => 'Echeveria elegans',
                'image' => 'echeveria_elegans.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Compact and easy to care for.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bamboo',
                'scientific_name' => 'Bambusoideae',
                'image' => 'bambusoideae.jpg',
                'watering_frequency' => 'Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Bi-Weekly',
                'additional_info' => 'Fast-growing and versatile.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ivy',
                'scientific_name' => 'Hedera helix',
                'image' => 'hedera_helix.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Great for hanging baskets.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jade Plant',
                'scientific_name' => 'Crassula ovata',
                'image' => 'crassula_ovata.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Known for its thick, glossy leaves.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Violet',
                'scientific_name' => 'Saintpaulia',
                'image' => 'saintpaulia.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Shade',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Produces beautiful flowers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orchid',
                'scientific_name' => 'Phalaenopsis',
                'image' => 'phalaenopsis.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Monthly',
                'additional_info' => 'Known for its elegant flowers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bromeliad',
                'scientific_name' => 'Bromeliaceae',
                'image' => 'bromeliaceae.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Colorful and low maintenance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Croton',
                'scientific_name' => 'Codiaeum variegatum',
                'image' => 'codiaeum_variegatum.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Known for its colorful foliage.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dragon Tree',
                'scientific_name' => 'Dracaena marginata',
                'image' => 'dracaena_marginata.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Tolerates low light.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Parlor Palm',
                'scientific_name' => 'Chamaedorea elegans',
                'image' => 'chamaedorea_elegans.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Great for small spaces.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cast Iron Plant',
                'scientific_name' => 'Aspidistra elatior',
                'image' => 'aspidistra_elatior.jpg',
                'watering_frequency' => 'Bi-Weekly',
                'sunlight' => 'Indirect Light',
                'soil_type' => 'Sandy',
                'fertilizing' => 'Quarterly',
                'additional_info' => 'Very hardy and low maintenance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
